steps:
  # Step 1: Authenticate Docker with Artifact Registry
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Step 2: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/k8s-assignment-441200/container1:latest",
        ".",
      ]

  # Step 3: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/k8s-assignment-441200/container1:latest",
      ]

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY
