steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/cloudcomputing-441122/container1:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/cloudcomputing-441122/container1:latest']

options:
  logging: CLOUD_LOGGING_ONLY
