steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/k8s-assignment-441200/container1:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/k8s-assignment-441200/container1:latest']

options:
  logging: CLOUD_LOGGING_ONLY